#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import print_function
import sys
import os
import traceback

script_dir = os.path.dirname(os.path.realpath(__file__))
parent_dir = os.path.join(script_dir,"..")

sys.path.insert(0,script_dir)
sys.path.insert(0,parent_dir)

try:
    import paragnosis
    paragnosis.main()

except Exception as error:
    print(traceback.format_exc())
    print(str(error))
    sys.exit(1)

